
server:
   port: 9091
spring:
  application:
    name: Employee-Service
  datasource:
    url: jdbc:mysql://localhost:3306/TheEmployees?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NkweMapoulo@1
  jpa:
    hibernate:
      ddl-auto: update
      
      

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
